#!/usr/bin/env zsh

export NXJ_HOME=~/.leJOS_NXJ
export LEJOS_NXT_JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home
export PATH=$NXJ_HOME/bin:$PATH

DOTFILES_ROOT=sed_dotfiles_root
ANTIGEN_ZSH="$DOTFILES_ROOT/zsh/antigen/antigen.zsh"
