# plugins can read the versions files used by other version managers (if enabled by the plugin)
# for example, .nvmrc in the case of node's nvm
legacy_version_file = true
legacy_version_file_disable_tools = []

# configure `mise install` to always keep the downloaded archive
always_keep_download = false
always_keep_install = false

# configure how frequently (in minutes) to fetch updated plugin repository changes
# this is updated whenever a new runtime is installed
# (note: this isn't currently implemented but there are plans to add it: https://github.com/jdx/mise/issues/128)
plugin_autoupdate_last_check_duration = '1 week'

# config files with these prefixes will be trusted by default
trusted_config_paths = []

verbose = false
asdf_compat = false
jobs = 4
raw = false
yes = false

not_found_auto_install = true
task_output = "prefix"
paranoid = false

disable_default_shorthands = false
disable_tools = []

